# -*- coding: utf-8 -*-
"""Sistema de Controle de Alunos e Notas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXIX-UiUDLtPjumBT0u5WkuGgL21l_wt
"""



alunos = {}
nomes_cadastrados = set()
def cadastrar_aluno():
    matricula = input("Digite a matrícula do aluno: ").strip()
    if matricula in alunos:
        print("Matrícula já cadastrada!")
        return
    nome = input("Digite o nome do aluno: ").strip().capitalize()
    if nome in nomes_cadastrados:
        print("Esse aluno já foi cadastrado!")
        return
    alunos[matricula] = ()
    nomes_cadastrados.add(nome)
    print(f"Aluno '{nome}' (Matrícula {matricula}) cadastrado com sucesso!\n")
def registrar_notas():
    matricula = input("Digite a matrícula do aluno: ").strip()
    if matricula not in alunos:
        print("Aluno não encontrado.")
        return
    notas_temp = []
    print("Digite as três notas do aluno:")
    for i in range(3):
        try:
            nota = float(input(f"Nota {i+1}: "))
            notas_temp.append(nota)
        except ValueError:
            print("Entrada inválida! Digite apenas números.")
            return
    alunos[matricula] = tuple(notas_temp)
    print(f"Notas registradas com sucesso para o aluno de matrícula {matricula}!\n")
def calcular_media(notas):
    if not notas:
        return 0.0
    return sum(notas) / len(notas)
def listar_alunos_medias():
    if not alunos:
        print("Nenhum aluno cadastrado.\n")
        return
    print("\n--- LISTA DE ALUNOS E MÉDIAS ---")
    for matricula, notas in alunos.items():
        media = calcular_media(notas)
        print(f"Matrícula: {matricula} | Notas: {notas} | Média: {media:.2f}")
    print("--------------------------------\n")
def buscar_aluno():
    matricula = input("Digite a matrícula do aluno: ").strip()
    if matricula in alunos:
        notas = alunos[matricula]
        media = calcular_media(notas)
        print(f"Aluno encontrado!\nMatrícula: {matricula}\nNotas: {notas}\nMédia: {media:.2f}\n")
    else:
        print("Aluno não encontrado.\n")
def mostrar_aprovados_reprovados():
    if not alunos:
        print("Nenhum aluno cadastrado.\n")
        return
    print("\n--- APROVADOS E REPROVADOS ---")
    for matricula, notas in alunos.items():
        media = calcular_media(notas)
        status = "Aprovado" if media >= 7 else "eprovado"
        print(f"Matrícula: {matricula} | Média: {media:.2f} | {status}")
    print("--------------------------------\n")
def relatorios():
    if not alunos:
        print("Nenhum aluno cadastrado.\n")
        return
    while True:
        print("""
RELATÓRIOS DISPONÍVEIS
1 - Alunos cadastrados
2 - Médias individuais
3 - Aprovados e Reprovados
0 - Voltar ao menu principal
""")
        opcao = input("Escolha uma opção: ")
        if opcao == "1":
            print("\n--- ALUNOS CADASTRADOS ---")
            for matricula in alunos:
                print(f"Matrícula: {matricula}")
            print("----------------------------\n")
        elif opcao == "2":
            listar_alunos_medias()
        elif opcao == "3":
            mostrar_aprovados_reprovados()
        elif opcao == "0":
            print("Voltando ao menu principal...\n")
            break
        else:
            print("Opção inválida. Tente novamente.")
def menu():
    while True:
        print("""
MENU PRINCIPAL
1 - Cadastrar aluno
2 - Registrar notas
3 - Listar alunos e médias
4 - Buscar aluno
5 - Mostrar aprovados e reprovados
6 - Relatórios
0 - Sair
""")
        opcao = input("Escolha uma opção: ")
        if opcao == "1":
            cadastrar_aluno()
        elif opcao == "2":
            registrar_notas()
        elif opcao == "3":
            listar_alunos_medias()
        elif opcao == "4":
            buscar_aluno()
        elif opcao == "5":
            mostrar_aprovados_reprovados()
        elif opcao == "6":
            relatorios()
        elif opcao == "0":
            print("Saindo do sistema. Até logo!")
            break
        else:
            print("Opção inválida! Tente novamente.")
menu()