# -*- coding: utf-8 -*-
"""Sistema de Cadastro de Produtos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14MOwC2dvPRdtU9EqPztY6MnaEP9UQLCh
"""

categorias = ("Alimentos", "Limpeza", "Bebidas")
estoque = []
codigos_cadastrados = set()
def cadastrar_produto():
    try:
        codigo = int(input("Digite o código do produto: "))
        if codigo in codigos_cadastrados:
            print("Código já cadastrado! Tente novamente.")
            return
        nome = input("Digite o nome do produto: ").strip().capitalize()
        preco = float(input("Digite o preço do produto: "))
        quantidade = int(input("Digite a quantidade em estoque: "))
        print("\nCategorias disponíveis:")
        for i, cat in enumerate(categorias):
            print(f"{i+1} - {cat}")
        cat_index = int(input("Escolha o número da categoria: ")) - 1

        if cat_index not in range(len(categorias)):
            print("Categoria inválida!")
            return
        produto = {
            "codigo": codigo,
            "nome": nome,
            "preco": preco,
            "quantidade": quantidade,
            "categoria": categorias[cat_index]
        }
        estoque.append(produto)
        codigos_cadastrados.add(codigo)
        print(f"Produto '{nome}' cadastrado com sucesso!\n")

    except ValueError:
        print("Entrada inválida! Certifique-se de digitar números válidos.")
def listar_produtos():
    if not estoque:
        print("Nenhum produto cadastrado.\n")
        return
    print("\n--- LISTA DE PRODUTOS ---")
    for produto in estoque:
        print(f"Código: {produto['codigo']}, Nome: {produto['nome']}, "
              f"Preço: R${produto['preco']:.2f}, Quantidade: {produto['quantidade']}, "
              f"Categoria: {produto['categoria']}")
    print("--------------------------\n")
def buscar_produto():
    try:
        codigo = int(input("Digite o código do produto para buscar: "))
        for produto in estoque:
            if produto["codigo"] == codigo:
                print(f"\nProduto encontrado: {produto}")
                return
        print("Produto não encontrado.")
    except ValueError:
        print("Digite um código válido.")
def atualizar_produto():
    try:
        codigo = int(input("Digite o código do produto para atualizar: "))
        for produto in estoque:
            if produto["codigo"] == codigo:
                print(f"Produto atual: {produto}")
                produto["nome"] = input("Novo nome (ou Enter para manter): ") or produto["nome"]
                preco_input = input("Novo preço (ou Enter para manter): ")
                if preco_input:
                    produto["preco"] = float(preco_input)
                qtd_input = input("Nova quantidade (ou Enter para manter): ")
                if qtd_input:
                    produto["quantidade"] = int(qtd_input)
                print("Produto atualizado com sucesso!\n")
                return
        print("Produto não encontrado.")
    except ValueError:
        print("Entrada inválida.")
def excluir_produto():
    try:
        codigo = int(input("Digite o código do produto para excluir: "))
        for produto in estoque:
            if produto["codigo"] == codigo:
                estoque.remove(produto)
                codigos_cadastrados.remove(codigo)
                print(f"🗑️ Produto '{produto['nome']}' removido com sucesso!\n")
                return
        print("Produto não encontrado.")
    except ValueError:
        print("Digite um código válido.")
def menu():
    while True:
        print("""
MENU
1 - Cadastrar produto
2 - Listar produtos
3 - Buscar produto
4 - Atualizar produto
5 - Excluir produto
0 - Sair
""")
        opcao = input("Escolha uma opção: ")

        if opcao == "1":
            cadastrar_produto()
        elif opcao == "2":
            listar_produtos()
        elif opcao == "3":
            buscar_produto()
        elif opcao == "4":
            atualizar_produto()
        elif opcao == "5":
            excluir_produto()
        elif opcao == "0":
            print("Saindo do sistema. Até logo!")
            break
        else:
            print("Opção inválida! Tente novamente.")
menu()